/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */
/**
 * @file	req_getcred.c
 *
 * This file contains function relating to the PBS credential system,
 * it includes the major functions:
 *   req_authenResvPort - Authenticate a user connection based on pbs_iff  (new)
 *   req_connect    - validate the credential in a Connection Request (old)
 */
#include <pbs_config.h>   /* the master config generated by configure */

#include <sys/types.h>
#include <string.h>
#include "libpbs.h"
#include "server_limits.h"
#include "list_link.h"
#include "attribute.h"
#include "credential.h"
#include "net_connect.h"
#include "batch_request.h"
#include "pbs_share.h"
#include <security/pam_appl.h>
#include <stdio.h>
#include "log.h"
#include <assert.h>

/* External Global Data Items Referenced */

extern time_t time_now;

extern pbs_list_head svr_allconns;
extern int max_connection;

char user_passwd[256];
void read_from_user_home(char *username, char *host) {
	
	FILE *fp = popen("ssh username@host type 'C:\\Users\\username\\cred.txt'", "r");
	fgets(user_passwd, 256, fp) ;
}

int test_conv(int num_msg, const struct pam_message **msg,
        struct pam_response **resp, void *appdata_ptr) {
		
    const struct pam_message* msg_ptr = *msg;
    struct pam_response * resp_ptr = NULL;
    int x = 0;

    *resp = calloc(sizeof(struct pam_response), num_msg);
    for (x = 0; x < num_msg; x++, msg_ptr++){
        char* resp_str;
        switch (msg_ptr->msg_style){
            case PAM_PROMPT_ECHO_OFF:
            case PAM_PROMPT_ECHO_ON:
                resp_str = user_passwd;
                resp[x]->resp= strdup(resp_str);
                break;

            case PAM_ERROR_MSG:
            case PAM_TEXT_INFO:
                printf("PAM: %s\n", msg_ptr->msg);
                break;

            default:
                assert(0);

        }
    }
    return PAM_SUCCESS;
}

int validate_from_sssd(struct batch_request *preq) {
	int status;
	struct pam_conv conv;
	pam_handle_t* handle;

	read_from_user_home(preq->rq_user, preq->rq_host) ;
	conv.conv=test_conv;

	status = pam_start("passwd", preq->rq_user, &conv, &handle ) ;
	if (status != PAM_SUCCESS) {
		log_event(PBSEVENT_DEBUG, PBS_EVENTCLASS_SERVER, LOG_INFO,
				preq->rq_user, "Pam start failed");
		return 1;
	}
	status = pam_authenticate(handle, 0) ;
	if (status != PAM_SUCCESS) {
		log_event(PBSEVENT_DEBUG, PBS_EVENTCLASS_SERVER, LOG_INFO,
				preq->rq_user, ": Pam authentication failed");
		return 1;
	}
	status = pam_acct_mgmt(handle, 0);
	if (status != PAM_SUCCESS) {
		log_event(PBSEVENT_DEBUG, PBS_EVENTCLASS_SERVER, LOG_INFO,
				preq->rq_user, "Pam pam_acct_mgmt failed");
		return 1;
	}
	
	return 0;
}





/* Global Data Home in this file */

/**
 * @brief
 * 		req_connect - process a Connection Request
 * 		Almost does nothing.
 *
 * @param[in]	preq	- Connection Request
 */

void
req_connect(struct batch_request *preq)
{
	conn_t *conn = get_conn(preq->rq_conn);
	int validated_user ;

	if (!conn) {
		req_reject(PBSE_SYSTEM, 0, preq);
		return;
	}

	if (preq->rq_extend != NULL) {
		if (strcmp(preq->rq_extend, QSUB_DAEMON) == 0)
			conn->cn_authen |= PBS_NET_CONN_FROM_QSUB_DAEMON;
		else if (strcmp(preq->rq_extend, SC_DAEMON) == 0)
			conn->cn_authen |= PBS_NET_CONN_FROM_PRIVIL;
	}

	validated_user = validate_from_sssd(preq) ;
	if (validated_user == 0 && (conn->cn_authen &
		(PBS_NET_CONN_AUTHENTICATED|PBS_NET_CONN_FROM_PRIVIL))==0) 
		reply_ack(preq); // successfully authenticated with AD
	else
		req_reject(PBSE_BADCRED, 0, preq);

	if ((conn->cn_authen &
		(PBS_NET_CONN_AUTHENTICATED|PBS_NET_CONN_FROM_PRIVIL))==0) {
		reply_ack(preq);
	} else
		req_reject(PBSE_BADCRED, 0, preq);
}

/** 
 * @brief     
 *		req_authenResvPort - Authenticate a user connection based on the (new)
 *		pbs_iff information.  Pbs_iff will contact the server on a privileged
 *		port and identify the user who has made an existing, but yet unused,
 *		non-privileged connection.  This connection is marked as authenticated.
 *
 * @param[in]	preq	- Connection Request
 */

void
req_authenResvPort(struct batch_request *preq)
{
	pbs_net_t	req_addr;
	conn_t		*cp;
	uint		authrequest_port = preq->rq_ind.rq_authen_resvport.rq_port;

	cp = get_conn(preq->rq_conn);
	if (!cp) {
		req_reject(PBSE_SYSTEM, 0, preq);
		return;
	}

	req_addr = cp->cn_addr;

	/*
	 * find the socket whose client side is bound to the port named
	 * in the request
	 */

	for (cp = (conn_t *)GET_NEXT(svr_allconns); cp; cp = GET_NEXT(cp->cn_link)) {
		if (authrequest_port == cp->cn_port && req_addr == cp->cn_addr) {
			if ((cp->cn_authen & (PBS_NET_CONN_AUTHENTICATED | PBS_NET_CONN_FROM_PRIVIL)) == 0) {
				(void) strcpy(cp->cn_username, preq->rq_user);
				(void)strcpy(cp->cn_hostname, preq->rq_host);
				/* time stamp just for the record */
				cp->cn_timestamp = time_now;
				cp->cn_authen |= PBS_NET_CONN_AUTHENTICATED;
			}
			reply_ack(preq);
			return;
		}
	}
	req_reject(PBSE_BADCRED, 0, preq);
}
